# * Copyright 2016, Data61
# *
# * This software may be distributed and modified according to the terms of
# * the BSD 2-Clause license. Note that NO WARRANTY is provided.
# * See "LICENSE_BSD2.txt" for details.
# *
# * @TAG(NICTA_BSD)

# makefile for building, decompiling and validating seL4 here.

# optional configuration

CONFIG_OPTIMISATION_LEVEL=-O1

include Makefile.common
