#!/bin/bash

# Copyright 2022, Kry10 Limited.
# SPDX-License-Identifier: BSD-2-Clause

# Receive a job at the graph-refine back end.
# Takes arguments:
# - Job ID
# - Root of the graph-refine work area.
# Receives an xz-compressed tarball on standard input.

set -euo pipefail

JOB_ID="$1"
[ -n "${JOB_ID}" ] || exit 1

JOB_DIR="$2"
[ -d "${JOB_DIR}/jobs" ] || exit 1

mkdir "${JOB_DIR}/jobs/${JOB_ID}"
tar -xJf - -C "${JOB_DIR}/jobs/${JOB_ID}"
