# Copyright (c) 2022, Kry10 Limited
# SPDX-License-Identifier: BSD-2-Clause

name: Build

on:
  # FIXME: When RISC-V and ARM branches are merged to master:
  #        - switch the push trigger to master,
  #        - add schedule and pull_request triggers.
  push:
    branches:
      - ci-riscv64

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout graph-refine
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: seL4
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git
        env:
          CI_SSH: ${{ secrets.CI_SSH }}
        shell: bash
        run: |
          # Configure SSH access and Git identity
          eval $(ssh-agent)
          ssh-add -q - <<< "${CI_SSH}"
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "${GITHUB_ENV}"
          git config --global user.name "seL4 CI"
          git config --global user.email "ci@sel4.systems"
      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install Cachix
        uses: cachix/cachix-action@v10
        with:
          name: sel4-bv
          authToken: "${{ secrets.BV_CACHIX_AUTH_TOKEN }}"
      - name: Build graph-refine
        run: nix-build -A graph-refine-image -o graph-refine-image nix/graph-refine.nix
      - name: Load and tag graph-refine image
        run: |
          ./graph-refine-image | docker load
          IMAGE_TAG="$(docker image ls --format '{{.Tag}}' graph-refine)"
          docker tag "graph-refine:$IMAGE_TAG" ghcr.io/sel4/graph-refine-riscv64:latest
          docker tag "graph-refine:$IMAGE_TAG" ghcr.io/sel4/graph-refine-riscv64:"$IMAGE_TAG"
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Checkout HOL4 and polyml
        run: decompiler/setup-decompiler.py checkout --upstream --ssh
      - name: Build decompiler
        run: nix-build -A decompiler-image -o decompiler-image decompiler
      - name: Load and tag decompiler image
        run: |
          ./decompiler-image | docker load
          IMAGE_TAG="$(docker image ls --format '{{.Tag}}' decompiler)"
          docker tag "decompiler:$IMAGE_TAG" ghcr.io/sel4/decompiler:latest
          docker tag "decompiler:$IMAGE_TAG" ghcr.io/sel4/decompiler:"$IMAGE_TAG"
      - name: Push Docker images
        if: github.event_name == 'push' || github.event_name == 'schedule'
        run: |
          docker push --all-tags ghcr.io/sel4/graph-refine-riscv64
          docker push --all-tags ghcr.io/sel4/decompiler
      - name: Push upstream branches
        if: github.event_name == 'push' || github.event_name == 'schedule'
        run: |
          (cd decompiler/src/HOL4 && git push)
          (cd decompiler/src/polyml && git push)
